CREATE DATABASE IF NOT EXISTS mensajeria
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE mensajeria;

CREATE TABLE IF NOT EXISTS envios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    destinatario VARCHAR(120) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
